const METHODS = { browser: ["runCalendarSettings", "runScheduleViews", "runCalendarSharing", "deleteSchedule", "close"], db: ["prepareOwnedData", "awaitScheduleNotifications", "collectCalendarEvidence", "cleanupOwnedData"] };
const PROTECTED = new Set(["admin", "cyhuh", "ysla"]);
const SENSITIVE = /password|hash|token|cookie|authorization|secret|set-cookie|storage(?:key|path)/i;
const AUDITS = ["workspace.schedule.created", "workspace.schedule.updated", "workspace.schedule.deleted", "workspace.calendar.created", "workspace.calendar.updated", "workspace.calendar.reordered", "workspace.calendar.default_changed", "workspace.calendar.deleted", "workspace.calendar.subscription.requested", "workspace.calendar.subscription.accepted", "workspace.calendar.subscription.cancelled", "workspace.calendar.subscription.rejected"];
const SHOTS = ["calendar-month.png", "calendar-week.png", "calendar-day.png", "calendar-list.png", "schedule-compose.png", "calendar-settings.png", "calendar-sharing.png"].map((name) => `screenshots/${name}`);
const DYNAMIC_KINDS = new Set(["user_calendar", "user_schedule_event", "user_schedule_attendee", "user_calendar_subscription", "user_schedule_notification_delivery", "notification", "notification_state", "monitoring_event"]);

function fail(code) { const error = new Error(code); error.code = code; return error; }
function noSecrets(value, path = "calendar") { if (!value || typeof value !== "object") return; for (const [key, item] of Object.entries(value)) { if (SENSITIVE.test(key)) throw fail(`SENSITIVE_FIELD_REJECTED:${path}.${key}`); if (item && typeof item === "object") noSecrets(item, `${path}.${key}`); } }
function includesRun(value, runId) { return typeof value === "string" && value.toLowerCase().includes(runId.toLowerCase()); }
function assertDrivers(browser, db) { if (!browser || !db) throw fail("LIVE_INPUT_REQUIRED"); noSecrets(browser); noSecrets(db); for (const name of METHODS.browser) if (typeof browser[name] !== "function") throw fail("LIVE_INPUT_REQUIRED"); for (const name of METHODS.db) if (typeof db[name] !== "function") throw fail("LIVE_INPUT_REQUIRED"); }
function assertSession(session, user) { const ids = (Array.isArray(session) ? session : [session]).map((x) => x?.activeLoginId); if (ids.some((x) => PROTECTED.has(String(x).toLowerCase()))) throw fail("PROTECTED_ACCOUNT_SESSION_REJECTED"); if (!ids.includes(user.loginId)) throw fail("DISPOSABLE_SESSION_REQUIRED"); }
function assertActions(actual, expected) { const set = new Set(actual ?? []); if (!expected.every((x) => set.has(x))) throw fail("ACTION_EVIDENCE_INCOMPLETE"); }
function assertShots(actual, expected) { if (!Array.isArray(actual) || actual.length !== expected.length || new Set(actual).size !== actual.length || !expected.every((x) => actual.includes(x))) throw fail("SCREENSHOT_EVIDENCE_INCOMPLETE"); }
function assertNetwork(records) { if (!Array.isArray(records) || !records.length) throw fail("NETWORK_EVIDENCE_INCOMPLETE"); for (const row of records) { if (JSON.stringify(Object.keys(row).sort()) !== JSON.stringify(["method", "path", "status"])) throw fail("NETWORK_FIELDS_INVALID"); if (typeof row.path !== "string" || !row.path.startsWith("/api/v1/workspace/") || row.path.includes("://") || row.path.includes("?") || !/^(GET|POST|PUT|PATCH|DELETE)$/.test(row.method) || !Number.isInteger(row.status) || row.status < 200 || row.status >= 300) throw fail("NETWORK_NOT_SAME_ORIGIN_RELATIVE"); } }

function assertBase(candidate, runId) {
  noSecrets(candidate);
  if (candidate?.runId !== runId || !candidate.companyId || !Array.isArray(candidate.records)) throw fail("OWNERSHIP_CONTRACT_INVALID");
  if (candidate.records.some((x) => !["test_role", "test_user", "user_calendar"].includes(x.kind) || x.ownerRunId !== runId)) throw fail("PRECREATED_PRODUCT_ROW_REJECTED");
  const ids = new Set(candidate.records.map((x) => x.id)); if (ids.size !== candidate.records.length) throw fail("OWNERSHIP_CONTRACT_INVALID");
  const roles = candidate.records.filter((x) => x.kind === "test_role"), users = candidate.records.filter((x) => x.kind === "test_user"), calendars = candidate.records.filter((x) => x.kind === "user_calendar");
  if (roles.length !== 1 || users.length !== 2 || calendars.length !== 2 || JSON.stringify(roles[0].permissions) !== JSON.stringify(["profile:read"])) throw fail("IDENTITY_TOPOLOGY_INVALID");
  const owner = users.find((x) => x.purpose === "owner"), collaborator = users.find((x) => x.purpose === "collaborator");
  if (!owner || !collaborator) throw fail("IDENTITY_TOPOLOGY_INVALID");
  for (const user of users) if (user.roleId !== roles[0].id || user.companyId !== candidate.companyId || user.active !== true || !includesRun(user.name, runId) || !includesRun(user.loginId, runId) || !includesRun(user.email?.split("@")[0], runId)) throw fail("IDENTITY_TOPOLOGY_INVALID");
  if (!calendars.every((x) => x.isAutoDefault === true && x.version === 0 && [owner.id, collaborator.id].includes(x.userId))) throw fail("IDENTITY_TOPOLOGY_INVALID");
  return { ownership: { runId, companyId: candidate.companyId, records: [...candidate.records] }, owner, collaborator, role: roles[0], owned: new Map(candidate.records.map((x) => [x.id, x])) };
}
function addOwned(context, records, allowedKinds) { if (!Array.isArray(records) || !records.length) throw fail("DYNAMIC_OWNERSHIP_MISSING"); for (const row of records) { if (!DYNAMIC_KINDS.has(row.kind) || !allowedKinds.includes(row.kind) || row.ownerRunId !== context.ownership.runId || context.owned.has(row.id)) throw fail("DYNAMIC_OWNERSHIP_INVALID"); context.ownership.records.push(row); context.owned.set(row.id, row); } }
function assertMutations(items, network, context) { const routes = new Set(network.map((x) => `${x.method} ${x.path}`)); for (const item of items ?? []) { const ids = item.ids ?? [item.id]; if (!ids.length || ids.some((id) => !context.owned.has(id)) || !routes.has(`${item.method} ${item.path}`)) throw fail("MUTATION_OWNERSHIP_MISMATCH"); } }
function ownedDynamic(path, prefix, context, kind) { const match = path.match(new RegExp(`^${prefix}/([^/]+)$`)); if (!match) return false; if (context.owned.get(match[1])?.kind !== kind) throw fail("NETWORK_DYNAMIC_OWNERSHIP_MISMATCH"); return true; }

function validateSettings(result, context) {
  noSecrets(result); if (result?.status !== "PASS") throw fail("CALENDAR_COMPOSITE_INCOMPLETE"); assertSession(result.session, context.owner); assertActions(result.actions, ["calendar.settings.open", "calendar.create", "calendar.reread", "calendar.update", "calendar.reorder", "calendar.default.change", "calendar.delete"]); assertNetwork(result.network); addOwned(context, result.createdRecords, ["user_calendar"]);
  for (const row of result.network) { const staticOk = (row.path === "/api/v1/workspace/calendars" && ["GET", "POST"].includes(row.method)) || (row.path === "/api/v1/workspace/calendars/order" && row.method === "PUT"); if (!staticOk && !ownedDynamic(row.path, "/api/v1/workspace/calendars", context, "user_calendar")) throw fail("NETWORK_ROUTE_FAMILY_INCOMPLETE"); }
  const t = result.transitions; if (!t || t.updated.afterVersion !== t.updated.beforeVersion + 1 || t.updated.rereadVersion !== t.updated.afterVersion || t.updated.visibility !== "approval_required" || !t.updated.nameIncludesRunId || t.reordered.length !== 2 || t.defaultChanged.length !== 2 || [...t.reordered, ...t.defaultChanged].some((x) => x.afterVersion !== x.beforeVersion + 1) || t.deleted.afterVersion !== t.deleted.beforeVersion + 1 || t.deleted.status !== "deleted") throw fail("CALENDAR_VERSION_INVALID");
  assertMutations(result.mutationOwnership, result.network, context); assertShots(result.screenshots, [SHOTS[5]]); return result;
}
function validateSchedules(result, context) {
  noSecrets(result); if (result?.status !== "PASS") throw fail("CALENDAR_COMPOSITE_INCOMPLETE"); assertSession(result.session, context.owner); assertActions(result.actions, ["schedule.create", "schedule.reread", "schedule.update", "schedule.detail.reread", "calendar.month", "calendar.week", "calendar.day", "calendar.list", "calendar.previous", "calendar.next", "calendar.today", "calendar.search", "schedule.detail", "calendar.overflow.evaluate"]); assertNetwork(result.network); addOwned(context, result.createdRecords, ["user_schedule_event", "user_schedule_attendee"]);
  for (const row of result.network) { const staticOk = row.path === "/api/v1/workspace/schedules" && ["GET", "POST"].includes(row.method); if (!staticOk && !ownedDynamic(row.path, "/api/v1/workspace/schedules", context, "user_schedule_event")) throw fail("NETWORK_DYNAMIC_OWNERSHIP_MISMATCH"); }
  const s = result.schedule, views = result.views; if (!s || context.owned.get(s.id)?.kind !== "user_schedule_event" || s.calendarId !== context.owned.get(s.id).calendarId || s.ownerId !== context.owner.id || JSON.stringify(s.attendeeIds) !== JSON.stringify([context.collaborator.id]) || !s.titleIncludesRunId || s.timezone !== "Asia/Seoul" || !s.repeatUntilPresent || s.alertMinutes !== 0 || !s.createReread || s.updateChangedFieldCount < 2 || !s.updateReread || !s.detailReread || !views || !["month", "week", "day", "list", "previous", "next", "today", "search", "detail"].every((x) => views[x] === true) || ![true, "NOT_APPLICABLE"].includes(views.overflow)) throw fail("SCHEDULE_STATE_INVALID");
  assertMutations(result.mutationOwnership, result.network, context); assertShots(result.screenshots, SHOTS.slice(0, 5)); return result;
}
function validateSharing(result, context) {
  noSecrets(result); if (result?.status !== "PASS") throw fail("CALENDAR_COMPOSITE_INCOMPLETE"); assertSession(result.sessions, context.owner); assertSession(result.sessions, context.collaborator); assertActions(result.actions, ["calendar.discover", "subscription.request", "subscription.accept", "shared.schedule.reread", "subscription.cancel", "subscription.rerequest", "subscription.reject"]); assertNetwork(result.network); addOwned(context, result.createdRecords, ["user_calendar_subscription"]);
  for (const row of result.network) { const staticOk = row.path === "/api/v1/workspace/calendars/discover" || row.path === "/api/v1/workspace/schedules" || (row.path === "/api/v1/workspace/calendar-subscriptions" && row.method === "POST"); const dynamic = row.path.match(/^\/api\/v1\/workspace\/calendar-subscriptions\/([^/]+)(?:\/(accept|reject))?$/); if (!staticOk && (!dynamic || context.owned.get(dynamic[1])?.kind !== "user_calendar_subscription")) throw fail(dynamic ? "NETWORK_DYNAMIC_OWNERSHIP_MISMATCH" : "NETWORK_ROUTE_FAMILY_INCOMPLETE"); }
  const expected = [["pending", 0], ["active", 1], ["cancelled", 2], ["pending", 3], ["rejected", 4]], s = result.subscription; if (!s || s.ownerId !== context.owner.id || s.subscriberId !== context.collaborator.id || !s.sharedScheduleReread || JSON.stringify(s.transitions.map((x) => [x.status, x.version])) !== JSON.stringify(expected)) throw fail("SUBSCRIPTION_TRANSITION_INVALID");
  assertMutations(result.mutationOwnership, result.network, context); assertShots(result.screenshots, [SHOTS[6]]); return result;
}
function validateDelivery(result, context) { noSecrets(result); if (result?.status !== "PASS") throw fail("CALENDAR_COMPOSITE_INCOMPLETE"); if (result.boundedWaitSeconds > 120 || result.boundedWaitSeconds < 1) throw fail("DELIVERY_WAIT_INVALID"); addOwned(context, result.createdRecords, ["user_schedule_notification_delivery", "notification", "notification_state", "monitoring_event"]); const rows = result.deliveries ?? []; if (rows.length !== 2 || new Set(rows.map((x) => x.id)).size !== 2 || new Set(rows.map((x) => x.recipientId)).size !== 2 || ![context.owner.id, context.collaborator.id].every((id) => rows.some((x) => x.recipientId === id)) || rows.some((x) => x.status !== "sent" || !x.occurrencePresent || x.alertMinutes !== 0 || context.owned.get(x.id)?.kind !== "user_schedule_notification_delivery") || result.foreignRecipientCount !== 0) throw fail("DELIVERY_EVIDENCE_INCOMPLETE"); return result; }
function validateDelete(result, context) { noSecrets(result); if (result?.status !== "PASS") throw fail("CALENDAR_COMPOSITE_INCOMPLETE"); assertSession(result.session, context.owner); assertActions(result.actions, ["schedule.delete", "schedule.deleted.reread"]); assertNetwork(result.network); if (!ownedDynamic(result.network[0]?.path, "/api/v1/workspace/schedules", context, "user_schedule_event") || result.network[0].method !== "DELETE" || result.schedule?.status !== "deleted" || !result.schedule.absentFromList) throw fail("SCHEDULE_DELETE_INVALID"); assertMutations(result.mutationOwnership, result.network, context); return result; }
function assertDb(e, context, runId) { noSecrets(e); if (e?.existingRowChanges !== 0 || !Array.isArray(e.rows) || e.rows.length !== context.owned.size || e.rows.some((x) => x.ownerRunId !== runId || context.owned.get(x.id)?.kind !== x.kind)) throw fail(e?.existingRowChanges ? "EXISTING_ROW_CHANGED" : "DB_EVIDENCE_NOT_RUN_OWNED"); const events = new Set((e.audits ?? []).map((x) => x.event)); if (!AUDITS.every((x) => events.has(x)) || e.audits.some((x) => x.ownerRunId !== runId || ![context.owner.id, context.collaborator.id].includes(x.actorId) || !context.owned.has(x.targetId))) throw fail("AUDIT_EVIDENCE_INCOMPLETE"); if (e.schedule?.status !== "deleted" || e.schedule.calendarId !== context.owned.get(e.schedule.id)?.calendarId || e.schedule.timezone !== "Asia/Seoul" || !e.schedule.createReread || !e.schedule.updateReread || e.subscription?.status !== "rejected" || e.subscription.version !== 4 || e.deliveries?.length !== 2) throw fail("DB_STATE_MISMATCH"); }
function sameFp(x) { return x?.before?.exists === false ? x.after?.exists === false : x?.after?.exists === true && x.before?.fingerprint && x.before.fingerprint === x.after.fingerprint; }
function assertCleanup(c, context, runId) { noSecrets(c); if (c?.runId !== runId || c.residualOwnedRows !== 0 || c.residualOwnedAudit !== 0 || c.residualNotifications !== 0 || c.residualMonitoringEvents !== 0 || c.residualDeliveries !== 0 || c.orderVerified !== true || c.sessionsClosed !== true || c.existingRowChanges !== 0) throw fail("CLEANUP_INCOMPLETE"); if (context) { const ids = context.ownership.records.filter((x) => ["test_role", "test_user"].includes(x.kind)); if (c.disposableIdentities?.length !== ids.length || c.disposableIdentities.some((x) => x.active !== false || x.ownerRunId !== runId || !ids.some((i) => i.id === x.id && i.kind === x.kind))) throw fail("CLEANUP_INCOMPLETE"); } if (!["admin", "cyhuh", "ysla"].every((id) => sameFp(c.protectedAccounts?.find((x) => x.loginId === id))) || c.existingCalendarFingerprint?.before !== c.existingCalendarFingerprint?.after) throw fail("PROTECTED_ACCOUNT_CHANGED"); }

export async function runCalendar({ manifest, runId, browserDriver, dbDriver, evidenceDir }) { assertDrivers(browserDriver, dbDriver); const area = manifest.areas.find((x) => x.id === "calendar"); if (area?.status !== "READY" || area.adapter !== "calendar") throw fail("AREA_NOT_READY"); let context, settings, schedules, sharing, delivery, deleted, dbEvidence, cleanup, primary, closeError, cleanupError; try { context = assertBase(await dbDriver.prepareOwnedData({ runId }), runId); settings = validateSettings(await browserDriver.runCalendarSettings({ runId, origin: manifest.environment.userOrigin, evidenceDir, ownership: context.ownership }), context); schedules = validateSchedules(await browserDriver.runScheduleViews({ runId, origin: manifest.environment.userOrigin, evidenceDir, ownership: context.ownership }), context); sharing = validateSharing(await browserDriver.runCalendarSharing({ runId, origin: manifest.environment.userOrigin, evidenceDir, ownership: context.ownership }), context); delivery = validateDelivery(await dbDriver.awaitScheduleNotifications({ runId, ownership: context.ownership, timeoutSeconds: 120 }), context); deleted = validateDelete(await browserDriver.deleteSchedule({ runId, origin: manifest.environment.userOrigin, evidenceDir, ownership: context.ownership }), context); dbEvidence = await dbDriver.collectCalendarEvidence({ runId, ownership: context.ownership }); assertDb(dbEvidence, context, runId); } catch (error) { primary = error?.code ? error : fail("LIVE_EXECUTION_FAILED"); } finally { try { await browserDriver.close(); } catch { closeError = fail("BROWSER_CLOSE_FAILED"); } try { cleanup = await dbDriver.cleanupOwnedData({ runId, ownership: context?.ownership }); } catch { cleanupError = fail("CLEANUP_DRIVER_FAILED"); } } if (cleanupError) throw cleanupError; if (!cleanup) throw primary ?? fail("CLEANUP_REQUIRED"); assertCleanup(cleanup, context, runId); if (closeError) throw closeError; if (primary) throw primary; return { status: "PASS", areaId: "calendar", actions: { settings: settings.actions, schedules: schedules.actions, sharing: sharing.actions, delete: deleted.actions }, screenshots: [...schedules.screenshots, ...settings.screenshots, ...sharing.screenshots], network: [...settings.network, ...schedules.network, ...sharing.network, ...deleted.network], mutationOwnership: { settings: settings.mutationOwnership, schedules: schedules.mutationOwnership, sharing: sharing.mutationOwnership, delete: deleted.mutationOwnership }, dbAudit: dbEvidence, delivery, cleanup }; }
