const METHODS = { browser: ["runOwnerSetupFlow", "runViewerFlow", "runOwnerShareUpgradeFlow", "runEditorFlow", "runOwnerFinalizeFlow", "close"], db: ["prepareOwnedData", "collectFilesEvidence", "cleanupOwnedData"], storage: ["collectFilesStorageEvidence", "cleanupOwnedStorage"] };
const PROTECTED = new Set(["admin", "cyhuh", "ysla"]);
const SENSITIVE = /password|hash|token|cookie|authorization|secret|set-cookie|storagekey|storagepath|internalpath|filesystempath|absolutepath|checksum|rawbytes|filebytes|filecontent/i;
const SHOTS = ["files-mine-folder.png", "files-upload-detail.png", "files-share-viewer.png", "files-shared-viewer.png", "files-shared-editor.png", "files-version-history.png", "files-trash.png"].map((name) => `screenshots/${name}`);
const KINDS = new Set(["file_folder", "workspace_file", "file_version", "file_share", "file_favorite"]);
const OWNER_PERMISSIONS = { download: true, newVersion: true, rename: true, move: true, share: true, favorite: true, trash: true, restore: true };
const VIEWER_PERMISSIONS = { download: true, newVersion: false, rename: false, move: false, share: false, favorite: true, trash: false, restore: false };
const EDITOR_PERMISSIONS = { download: true, newVersion: true, rename: true, move: false, share: false, favorite: true, trash: false, restore: false };

function fail(code) { const error = new Error(code); error.code = code; return error; }
function scan(value, at = "files") { if (!value || typeof value !== "object") return; for (const [key, item] of Object.entries(value)) { if (SENSITIVE.test(key)) throw fail(`SENSITIVE_FIELD_REJECTED:${at}.${key}`); if (item && typeof item === "object") scan(item, `${at}.${key}`); } }
function same(a, b) { return JSON.stringify(a) === JSON.stringify(b); }
function count(rows, keyOf) { const map = new Map(); for (const row of rows) { const key = keyOf(row); map.set(key, (map.get(key) ?? 0) + 1); } return map; }
function sameCounts(a, b) { if (a.size !== b.size) return false; for (const [key, value] of a) if (b.get(key) !== value) return false; return true; }
function stable(item) { return item?.before?.exists === item?.after?.exists && (!item?.before?.exists || item.before.fingerprint === item.after.fingerprint); }
function assertDrivers(browser, db, storage) { if (!browser || !db || !storage) throw fail("LIVE_INPUT_REQUIRED"); scan(browser); scan(db); scan(storage); for (const name of METHODS.browser) if (typeof browser[name] !== "function") throw fail("LIVE_INPUT_REQUIRED"); for (const name of METHODS.db) if (typeof db[name] !== "function") throw fail("LIVE_INPUT_REQUIRED"); for (const name of METHODS.storage) if (typeof storage[name] !== "function") throw fail("LIVE_INPUT_REQUIRED"); }
function assertSession(session, user) { const login = String(session?.activeLoginId ?? "").toLowerCase(); if (PROTECTED.has(login)) throw fail("PROTECTED_ACCOUNT_SESSION_REJECTED"); if (session?.activeUserId !== user.id || login !== user.loginId.toLowerCase()) throw fail("DISPOSABLE_SESSION_REQUIRED"); }
function assertActions(actual, required) { const set = new Set(actual ?? []); if (!required.every((item) => set.has(item))) throw fail("ACTION_EVIDENCE_INCOMPLETE"); }
function assertShots(actual, required) { if (!Array.isArray(actual) || actual.length !== required.length || new Set(actual).size !== actual.length || !required.every((item) => actual.includes(item))) throw fail("SCREENSHOT_EVIDENCE_INCOMPLETE"); }
function assertFixture(fixture) { if (!fixture?.fileNameIncludesRunId || fixture.extension !== ".txt" || fixture.mimeType !== "text/plain" || !Number.isInteger(fixture.byteSize) || fixture.byteSize < 1 || fixture.byteSize > 1024 || fixture.expectedBytesMatch !== true) throw fail("FILE_FIXTURE_INVALID"); }

function assertBase(value, runId) {
  scan(value); if (value?.runId !== runId || !value.companyId || !Array.isArray(value.records)) throw fail("OWNERSHIP_CONTRACT_INVALID");
  if (value.precreatedBlobs !== 0) throw fail("PRECREATED_BLOB_REJECTED");
  if (value.records.some((x) => !["test_role", "test_user", "user_calendar"].includes(x.kind) || x.ownerRunId !== runId)) throw fail("PRECREATED_PRODUCT_ROW_REJECTED");
  if (new Set(value.records.map((x) => x.id)).size !== value.records.length) throw fail("OWNERSHIP_CONTRACT_INVALID");
  const roles = value.records.filter((x) => x.kind === "test_role"), users = value.records.filter((x) => x.kind === "test_user"), calendars = value.records.filter((x) => x.kind === "user_calendar");
  if (roles.length !== 1 || !same(roles[0].permissions, ["profile:read"]) || users.length !== 2 || calendars.length !== 2) throw fail("IDENTITY_TOPOLOGY_INVALID");
  const purposes = new Map(users.map((x) => [x.purpose, x])); if (!purposes.has("owner") || !purposes.has("collaborator")) throw fail("IDENTITY_TOPOLOGY_INVALID");
  if (users.some((x) => PROTECTED.has(String(x.loginId).toLowerCase()) || x.roleId !== roles[0].id || x.companyId !== value.companyId || x.departmentId !== value.referenceDepartment?.id || !x.active || !String(x.loginId).toLowerCase().includes(runId.toLowerCase()))) throw fail("IDENTITY_TOPOLOGY_INVALID");
  if (!value.referenceDepartment?.existing || !value.referenceDepartment.active || value.referenceDepartment.companyId !== value.companyId || !calendars.every((x) => x.isAutoDefault && x.companyId === value.companyId && users.some((u) => u.id === x.userId)) || new Set(calendars.map((x) => x.userId)).size !== 2) throw fail("IDENTITY_TOPOLOGY_INVALID");
  return { ownership: { ...value, records: [...value.records] }, users: purposes, owned: new Map(value.records.map((x) => [x.id, x])) };
}
function addOwned(context, rows, allowed) { if (!Array.isArray(rows) || !rows.length) throw fail("DYNAMIC_OWNERSHIP_MISSING"); for (const row of rows) { if (!KINDS.has(row.kind) || !allowed.includes(row.kind) || row.ownerRunId !== context.ownership.runId || row.createdInBrowser !== true || context.owned.has(row.id)) throw fail("DYNAMIC_OWNERSHIP_INVALID"); context.owned.set(row.id, row); context.ownership.records.push(row); } }
function owned(context, id, kind) { const row = context.owned.get(id); if (row?.kind !== kind) throw fail("NETWORK_DYNAMIC_OWNERSHIP_MISMATCH"); return row; }
function assertNetwork(rows, context) {
  if (!Array.isArray(rows) || !rows.length) throw fail("NETWORK_EVIDENCE_INCOMPLETE");
  for (const row of rows) {
    if (!same(Object.keys(row).sort(), ["method", "path", "status"])) throw fail("NETWORK_FIELDS_INVALID");
    if (!/^(GET|POST|PATCH|PUT|DELETE)$/.test(row.method) || !Number.isInteger(row.status) || row.status < 200 || row.status >= 300 || typeof row.path !== "string" || !row.path.startsWith("/api/v1/workspace/") || row.path.includes("://") || row.path.includes("?")) throw fail("NETWORK_NOT_SAME_ORIGIN_RELATIVE");
    const folder = row.path.match(/^\/api\/v1\/workspace\/file-folders\/([^/]+)$/), file = row.path.match(/^\/api\/v1\/workspace\/files\/([^/]+)(?:\/(versions|restore|favorite|shares|download))?$/);
    const ok = (row.path === "/api/v1/workspace/file-folders" && ["GET", "POST"].includes(row.method)) || (row.path === "/api/v1/workspace/files" && ["GET", "POST"].includes(row.method)) || (folder && ["PATCH", "DELETE"].includes(row.method)) || (file && ((!file[2] && ["GET", "PATCH", "DELETE"].includes(row.method)) || (file[2] === "versions" && ["GET", "POST"].includes(row.method)) || (file[2] === "restore" && row.method === "POST") || (file[2] === "favorite" && ["PUT", "DELETE"].includes(row.method)) || (file[2] === "shares" && row.method === "PUT") || (file[2] === "download" && row.method === "GET")));
    if (!ok) throw fail("NETWORK_ROUTE_FAMILY_INCOMPLETE");
    if (folder && context && context.owned.has(folder[1]) && context.owned.get(folder[1]).kind !== "file_folder") throw fail("NETWORK_DYNAMIC_OWNERSHIP_MISMATCH");
    if (file && context && context.owned.has(file[1]) && context.owned.get(file[1]).kind !== "workspace_file") throw fail("NETWORK_DYNAMIC_OWNERSHIP_MISMATCH");
    if ((folder && !context?.owned.has(folder[1])) || (file && !context?.owned.has(file[1]))) throw fail("NETWORK_DYNAMIC_OWNERSHIP_MISMATCH");
  }
}
function assertMutations(items, network, context) {
  if (!Array.isArray(items)) throw fail("MUTATION_EVIDENCE_INCOMPLETE"); const mutations = network.filter((x) => x.method !== "GET");
  if (items.length !== mutations.length || !sameCounts(count(items, (x) => `${x.method} ${x.path}`), count(mutations, (x) => `${x.method} ${x.path}`))) throw fail("MUTATION_EVIDENCE_INCOMPLETE");
  for (const item of items) { const ids = item.ids ?? [item.id]; if (!ids.length || ids.some((id) => !context.owned.has(id))) throw fail("MUTATION_OWNERSHIP_MISMATCH"); const folder = item.path.match(/^\/api\/v1\/workspace\/file-folders\/([^/]+)$/), file = item.path.match(/^\/api\/v1\/workspace\/files\/([^/]+)/); if (folder && folder[1] !== ids[0]) throw fail("MUTATION_OWNERSHIP_MISMATCH"); if (file && file[1] !== ids[0]) throw fail("MUTATION_OWNERSHIP_MISMATCH"); }
}
function assertPermission(actual, expected, denied = []) { if (!same(actual, expected)) throw fail("PERMISSION_CONTRACT_INVALID"); if (denied.length && !same([...denied].sort(), Object.entries(expected).filter(([, allowed]) => !allowed).map(([key]) => key).sort())) throw fail("PERMISSION_CONTRACT_INVALID"); }

function validateOwner(result, context) {
  scan(result); const owner = context.users.get("owner"), collaborator = context.users.get("collaborator"); if (result?.status !== "PASS") throw fail("FILES_COMPOSITE_INCOMPLETE"); assertSession(result.session, owner); assertActions(result.actions, ["files.open", "files.six.scopes", "files.three.column", "folder.create", "folder.rename", "file.v1.upload", "file.current.download", "file.rename.owner", "favorite.owner.set", "favorite.owner.clear", "share.viewer.save", "share.viewer.reread"]); addOwned(context, result.createdRecords, ["file_folder", "workspace_file", "file_version", "file_share", "file_favorite"]);
  const folder = result.createdRecords.find((x) => x.kind === "file_folder"), file = result.createdRecords.find((x) => x.kind === "workspace_file"), version = result.createdRecords.find((x) => x.kind === "file_version"), share = result.createdRecords.find((x) => x.kind === "file_share"), favorite = result.createdRecords.find((x) => x.kind === "file_favorite");
  if (!folder || !file || !version || !share || !favorite || folder.ownerUserId !== owner.id || file.ownerUserId !== owner.id || file.folderId !== folder.id || version.fileId !== file.id || version.versionNo !== 1 || version.creatorId !== owner.id || share.fileId !== file.id || share.targetUserId !== collaborator.id || share.permission !== "viewer" || PROTECTED.has(String(share.targetUserId).toLowerCase()) || favorite.fileId !== file.id || favorite.userId !== owner.id) throw fail(PROTECTED.has(String(share?.targetUserId).toLowerCase()) ? "PROTECTED_SHARE_TARGET_REJECTED" : "DYNAMIC_RELATION_INVALID");
  assertFixture(result.fixture); assertPermission(result.permissions, OWNER_PERMISSIONS); if (result.folder?.id !== folder.id || !result.folder.created || !result.folder.renamed || result.file?.id !== file.id || result.file.currentVersion !== 1 || !result.file.renamedByOwner || result.file.ownerFavoriteResidual !== 0 || result.share?.id !== share.id || result.share.targetUserId !== collaborator.id || result.share.permission !== "viewer" || !result.share.active || result.download?.versionNo !== 1 || !result.download.expectedBytesMatch) throw fail("FILE_STATE_INVALID");
  assertNetwork(result.network, context); assertMutations(result.mutationOwnership, result.network, context); assertShots(result.screenshots, SHOTS.slice(0, 3)); return result;
}
function validateViewer(result, context) {
  scan(result); const collaborator = context.users.get("collaborator"), file = [...context.owned.values()].find((x) => x.kind === "workspace_file"); if (result?.status !== "PASS") throw fail("FILES_COMPOSITE_INCOMPLETE"); assertSession(result.session, collaborator); assertActions(result.actions, ["files.shared.open", "file.viewer.select", "file.viewer.download", "favorite.viewer.set", "favorite.viewer.clear", "viewer.forbidden.controls.hidden"]); addOwned(context, result.createdRecords, ["file_favorite"]); const favorite = result.createdRecords[0]; if (favorite.fileId !== file.id || favorite.userId !== collaborator.id) throw fail("DYNAMIC_RELATION_INVALID"); assertPermission(result.permissions, VIEWER_PERMISSIONS, result.deniedActions); if (result.download?.versionNo !== 1 || !result.download.expectedBytesMatch) throw fail("DOWNLOAD_BYTES_MISMATCH"); assertNetwork(result.network, context); assertMutations(result.mutationOwnership, result.network, context); assertShots(result.screenshots, [SHOTS[3]]); return result;
}
function validateUpgrade(result, context) { scan(result); const owner = context.users.get("owner"), collaborator = context.users.get("collaborator"), share = [...context.owned.values()].find((x) => x.kind === "file_share"); if (result?.status !== "PASS") throw fail("FILES_COMPOSITE_INCOMPLETE"); assertSession(result.session, owner); assertActions(result.actions, ["share.editor.save", "share.editor.reread"]); if (result.share?.id !== share.id || result.share.targetUserId !== collaborator.id || result.share.permission !== "editor" || !result.share.active) throw fail("DYNAMIC_RELATION_INVALID"); share.permission = "editor"; assertNetwork(result.network, context); assertMutations(result.mutationOwnership, result.network, context); return result; }
function validateEditor(result, context) {
  scan(result); const collaborator = context.users.get("collaborator"), file = [...context.owned.values()].find((x) => x.kind === "workspace_file"), share = [...context.owned.values()].find((x) => x.kind === "file_share"); if (result?.status !== "PASS") throw fail("FILES_COMPOSITE_INCOMPLETE"); assertSession(result.session, collaborator); if (share.permission !== "editor") throw fail("PERMISSION_CONTRACT_INVALID"); assertActions(result.actions, ["files.shared.editor.reread", "file.rename.editor", "file.v2.upload", "file.v2.reread", "editor.forbidden.controls.hidden"]); addOwned(context, result.createdRecords, ["file_version"]); const version = result.createdRecords[0]; if (version.fileId !== file.id || version.versionNo !== 2 || version.creatorId !== collaborator.id) throw fail("VERSION_CONTRACT_INVALID"); assertFixture(result.fixture); assertPermission(result.permissions, EDITOR_PERMISSIONS, result.deniedActions); if (result.file?.id !== file.id || result.file.currentVersion !== 2 || !result.file.renamedByEditor) throw fail("FILE_STATE_INVALID"); assertNetwork(result.network, context); assertMutations(result.mutationOwnership, result.network, context); assertShots(result.screenshots, [SHOTS[4]]); return result;
}
function validateFinalize(result, context) {
  scan(result); const owner = context.users.get("owner"), file = [...context.owned.values()].find((x) => x.kind === "workspace_file"), folder = [...context.owned.values()].find((x) => x.kind === "file_folder"), share = [...context.owned.values()].find((x) => x.kind === "file_share"); if (result?.status !== "PASS") throw fail("FILES_COMPOSITE_INCOMPLETE"); assertSession(result.session, owner); assertActions(result.actions, ["file.version.history", "file.v1.historical.download", "file.v2.current.download", "file.move.root", "share.remove", "folder.delete", "file.trash", "file.restore", "file.trash.again", "trash.final.reread"]); assertPermission(result.permissions, OWNER_PERMISSIONS); if (result.file?.id !== file.id || result.file.folderId !== null || result.file.currentVersion !== 2 || result.file.finalStatus !== "deleted" || !result.file.recoverable || result.folder?.id !== folder.id || !result.folder.deleted || result.share?.id !== share.id || result.share.active !== false) throw fail("FILE_STATE_INVALID"); if (result.downloads?.length !== 2 || !same(result.downloads.map((x) => x.versionNo), [1, 2]) || result.downloads.some((x) => !x.expectedBytesMatch)) throw fail("DOWNLOAD_BYTES_MISMATCH"); assertNetwork(result.network, context); assertMutations(result.mutationOwnership, result.network, context); assertShots(result.screenshots, SHOTS.slice(5)); return result;
}

function validateDb(value, context) {
  scan(value); const owner = context.users.get("owner"), collaborator = context.users.get("collaborator"), folder = [...context.owned.values()].find((x) => x.kind === "file_folder"), file = [...context.owned.values()].find((x) => x.kind === "workspace_file"), versions = [...context.owned.values()].filter((x) => x.kind === "file_version"), share = [...context.owned.values()].find((x) => x.kind === "file_share");
  const expectedRows = [...context.owned.values()].filter((x) => ["file_folder", "workspace_file", "file_version", "file_share"].includes(x.kind)), ids = new Set(value?.rows?.map((x) => x.id) ?? []); if (!Array.isArray(value?.rows) || value.rows.length !== expectedRows.length || ids.size !== expectedRows.length || expectedRows.some((x) => !ids.has(x.id)) || value.rows.some((x) => x.ownerRunId !== context.ownership.runId || context.owned.get(x.id)?.kind !== x.kind) || value.existingRowChanges !== 0) throw fail("DB_EVIDENCE_NOT_RUN_OWNED");
  if (value.folder?.id !== folder.id || value.folder.ownerUserId !== owner.id || value.folder.companyId !== context.ownership.companyId || !value.folder.deleted || value.file?.id !== file.id || value.file.ownerUserId !== owner.id || value.file.companyId !== context.ownership.companyId || value.file.folderId !== null || value.file.status !== "deleted" || value.file.currentVersion !== 2 || !value.file.recoverable || value.versions?.length !== 2 || !value.versions.some((x) => x.id === versions.find((v) => v.versionNo === 1)?.id && x.creatorId === owner.id && x.byteSize === 31) || !value.versions.some((x) => x.id === versions.find((v) => v.versionNo === 2)?.id && x.creatorId === collaborator.id && x.byteSize === 43) || value.share?.id !== share.id || value.share.fileId !== file.id || value.share.targetUserId !== collaborator.id || value.share.permission !== "editor" || value.share.active !== false || value.favoriteRows !== 0) throw fail("DB_RELATION_INVALID");
  const expected = [["workspace.folder.created", owner.id, folder.id], ["workspace.folder.renamed", owner.id, folder.id], ["workspace.folder.deleted", owner.id, folder.id], ["workspace.file.uploaded", owner.id, file.id], ["workspace.file.downloaded", owner.id, file.id], ["workspace.file.downloaded", collaborator.id, file.id], ["workspace.file.downloaded", owner.id, file.id], ["workspace.file.renamed", owner.id, file.id], ["workspace.file.renamed", collaborator.id, file.id], ["workspace.file.version_created", collaborator.id, file.id], ["workspace.file.favorite_set", owner.id, file.id], ["workspace.file.favorite_set", collaborator.id, file.id], ["workspace.file.favorite_cleared", owner.id, file.id], ["workspace.file.favorite_cleared", collaborator.id, file.id], ["workspace.file.shared", owner.id, file.id], ["workspace.file.shared", owner.id, file.id], ["workspace.file.shared", owner.id, file.id], ["workspace.file.moved", owner.id, file.id], ["workspace.file.trashed", owner.id, file.id], ["workspace.file.trashed", owner.id, file.id], ["workspace.file.restored", owner.id, file.id]];
  if (!Array.isArray(value.audits) || value.audits.length !== 21 || !sameCounts(count(value.audits, (x) => `${x.event}\0${x.actorId}\0${x.targetId}`), count(expected, (x) => `${x[0]}\0${x[1]}\0${x[2]}`)) || value.audits.some((x) => x.ownerRunId !== context.ownership.runId || !x.reasonSafe)) throw fail("AUDIT_EVIDENCE_INCOMPLETE"); return value;
}
function validateStorage(value, context) { scan(value); const versions = [...context.owned.values()].filter((x) => x.kind === "file_version"), expected = new Map(versions.map((x) => [x.id, x.versionNo === 1 ? 31 : 43])); if (value?.blobCount !== 2 || !Array.isArray(value.blobs) || value.blobs.length !== 2 || new Set(value.blobs.map((x) => x.versionId)).size !== 2 || value.blobs.some((x) => !expected.has(x.versionId) || !x.exists || x.byteSize !== expected.get(x.versionId) || !x.expectedBytesMatch) || !value.withinRoot) throw fail("STORAGE_EVIDENCE_INCOMPLETE"); return value; }
function validateDbCleanup(value, context) { scan(value); const identities = [...context.owned.values()].filter((x) => ["test_role", "test_user"].includes(x.kind)); if (value?.runId !== context.ownership.runId || value.approved !== true || value.residualOwnedRows !== 0 || value.residualOwnedAudit !== 0 || !value.sessionsClosed || value.disposableIdentities?.length !== identities.length || value.disposableIdentities.some((x) => x.active !== false || x.ownerRunId !== context.ownership.runId || !identities.some((owned) => owned.id === x.id && owned.kind === x.kind)) || value.protectedAccounts?.length !== 3 || value.protectedAccounts.some((x) => !stable(x)) || value.existingFilesFingerprint?.before !== value.existingFilesFingerprint?.after) throw fail("DB_CLEANUP_INCOMPLETE"); return value; }
function validateStorageCleanup(value, context) { scan(value); const versions = [...context.owned.values()].filter((x) => x.kind === "file_version"); if (value?.runId !== context.ownership.runId || value.approved !== true || value.residualBlobs !== 0 || value.deletedBlobCount !== 2 || !value.withinRoot || value.broadDeleteUsed || value.deletedVersionIds?.length !== 2 || new Set(value.deletedVersionIds).size !== 2 || versions.some((x) => !value.deletedVersionIds.includes(x.id)) || value.existingStorageFingerprint?.before !== value.existingStorageFingerprint?.after) throw fail("STORAGE_CLEANUP_INCOMPLETE"); return value; }

export async function runFiles({ manifest, runId, browserDriver, dbDriver, storageDriver, cleanupApproved = false }) {
  assertDrivers(browserDriver, dbDriver, storageDriver); const area = manifest.areas.find((x) => x.id === "files"); if (!area || area.status !== "READY" || area.adapter !== "files") throw fail("AREA_NOT_READY");
  const context = assertBase(await dbDriver.prepareOwnedData({ runId }), runId); let owner, viewer, upgrade, editor, finalize, dbEvidence, storageEvidence, primaryError, closeError, dbCleanup, storageCleanup, dbCleanupError, storageCleanupError;
  try { owner = validateOwner(await browserDriver.runOwnerSetupFlow({ runId, ownership: context.ownership }), context); viewer = validateViewer(await browserDriver.runViewerFlow({ runId, ownership: context.ownership }), context); upgrade = validateUpgrade(await browserDriver.runOwnerShareUpgradeFlow({ runId, ownership: context.ownership }), context); editor = validateEditor(await browserDriver.runEditorFlow({ runId, ownership: context.ownership }), context); finalize = validateFinalize(await browserDriver.runOwnerFinalizeFlow({ runId, ownership: context.ownership }), context); dbEvidence = validateDb(await dbDriver.collectFilesEvidence({ runId, ownership: context.ownership }), context); storageEvidence = validateStorage(await storageDriver.collectFilesStorageEvidence({ runId, ownership: context.ownership }), context); } catch (error) { primaryError = error; }
  try { await browserDriver.close(); } catch (error) { closeError = error; }
  if (!cleanupApproved) { if (closeError) throw fail("BROWSER_CLOSE_FAILED"); if (primaryError) throw primaryError; throw fail("CLEANUP_APPROVAL_REQUIRED"); }
  try { dbCleanup = await dbDriver.cleanupOwnedData({ runId, ownership: context.ownership, approved: true }); } catch (error) { dbCleanupError = error; }
  try { storageCleanup = await storageDriver.cleanupOwnedStorage({ runId, ownership: context.ownership, approved: true }); } catch (error) { storageCleanupError = error; }
  if (storageCleanupError) throw fail("STORAGE_CLEANUP_FAILED"); if (dbCleanupError) throw fail("DB_CLEANUP_FAILED"); const cleanup = { db: validateDbCleanup(dbCleanup, context), storage: validateStorageCleanup(storageCleanup, context) }; if (closeError) throw fail("BROWSER_CLOSE_FAILED"); if (primaryError) throw primaryError;
  return { status: "PASS", areaId: "files", actions: { owner: owner.actions, viewer: viewer.actions, upgrade: upgrade.actions, editor: editor.actions, finalize: finalize.actions }, screenshots: [...owner.screenshots, ...viewer.screenshots, ...editor.screenshots, ...finalize.screenshots], network: [...owner.network, ...viewer.network, ...upgrade.network, ...editor.network, ...finalize.network], mutationOwnership: { owner: owner.mutationOwnership, viewer: viewer.mutationOwnership, upgrade: upgrade.mutationOwnership, editor: editor.mutationOwnership, finalize: finalize.mutationOwnership }, dbAudit: { db: dbEvidence, storage: storageEvidence }, cleanup };
}
