const METHODS = { browser: ["runMessengerRoomFlow", "runMessengerMessageFlow", "runMessengerReadFlow", "runInactiveParticipantFlow", "close"], db: ["prepareOwnedData", "collectMessengerEvidence", "cleanupOwnedData"], storage: ["collectMessengerStorageEvidence", "cleanupOwnedStorage"] };
const PROTECTED = new Set(["admin", "cyhuh", "ysla"]);
const SENSITIVE = /password|hash|token|cookie|authorization|secret|set-cookie|storagekey|internalpath|filesystempath|absolutepath/i;
const SHOTS = ["messenger-room-list.png", "messenger-room-create.png", "messenger-timeline.png", "messenger-attachment.png", "messenger-participants.png", "messenger-shared-files.png"].map((name) => `screenshots/${name}`);
const DYNAMIC = new Set(["messenger_room", "messenger_member", "messenger_staged_upload", "messenger_storage_object", "messenger_message", "messenger_attachment", "messenger_read"]);
const AUDIT_COUNTS = new Map([["messenger.room.created", 1], ["messenger.room.favorite_changed", 1], ["messenger.room.participants_changed", 1], ["messenger.message.sent", 2], ["messenger.room.read", 1]]);

function fail(code) { const error = new Error(code); error.code = code; return error; }
function noSecrets(value, at = "messenger") { if (!value || typeof value !== "object") return; for (const [key, item] of Object.entries(value)) { if (SENSITIVE.test(key)) throw fail(`SENSITIVE_FIELD_REJECTED:${at}.${key}`); if (item && typeof item === "object") noSecrets(item, `${at}.${key}`); } }
function includesRun(value, runId) { return typeof value === "string" && value.toLowerCase().includes(runId.toLowerCase()); }
function assertDrivers(browser, db, storage) { if (!browser || !db || !storage) throw fail("LIVE_INPUT_REQUIRED"); noSecrets(browser); noSecrets(db); noSecrets(storage); for (const name of METHODS.browser) if (typeof browser[name] !== "function") throw fail("LIVE_INPUT_REQUIRED"); for (const name of METHODS.db) if (typeof db[name] !== "function") throw fail("LIVE_INPUT_REQUIRED"); for (const name of METHODS.storage) if (typeof storage[name] !== "function") throw fail("LIVE_INPUT_REQUIRED"); }
function assertSession(session, expected) { const rows = Array.isArray(session) ? session : [session]; const ids = rows.map((x) => String(x?.activeLoginId ?? "").toLowerCase()); if (ids.some((id) => PROTECTED.has(id))) throw fail("PROTECTED_ACCOUNT_SESSION_REJECTED"); if (expected && !ids.includes(expected.loginId.toLowerCase())) throw fail("DISPOSABLE_SESSION_REQUIRED"); }
function assertActions(actual, expected) { const set = new Set(actual ?? []); if (!expected.every((item) => set.has(item))) throw fail("ACTION_EVIDENCE_INCOMPLETE"); }
function assertShots(actual, expected) { if (!Array.isArray(actual) || actual.length !== expected.length || new Set(actual).size !== actual.length || !expected.every((shot) => actual.includes(shot))) throw fail("SCREENSHOT_EVIDENCE_INCOMPLETE"); }
function assertNetwork(rows) { if (!Array.isArray(rows) || !rows.length) throw fail("NETWORK_EVIDENCE_INCOMPLETE"); for (const row of rows) { if (JSON.stringify(Object.keys(row).sort()) !== JSON.stringify(["method", "path", "status"])) throw fail("NETWORK_FIELDS_INVALID"); if (!/^(GET|POST|PATCH)$/.test(row.method) || !Number.isInteger(row.status) || row.status < 200 || row.status >= 300 || typeof row.path !== "string" || (!row.path.startsWith("/api/v1/messenger/") && !row.path.startsWith("/api/v1/admin/users/")) || row.path.includes("://") || row.path.includes("?")) throw fail("NETWORK_NOT_SAME_ORIGIN_RELATIVE"); } }
function countRoutes(rows) { const result = new Map(); for (const row of rows) { const key = `${row.method} ${row.path}`; result.set(key, (result.get(key) ?? 0) + 1); } return result; }
function sameCounts(a, b) { if (a.size !== b.size) return false; for (const [key, count] of a) if (b.get(key) !== count) return false; return true; }

function assertBase(value, runId) {
  noSecrets(value); if (value?.runId !== runId || !value.companyId || !Array.isArray(value.records)) throw fail("OWNERSHIP_CONTRACT_INVALID");
  if (value.records.some((x) => !["test_role", "test_user", "user_calendar"].includes(x.kind) || x.ownerRunId !== runId)) throw fail("PRECREATED_PRODUCT_ROW_REJECTED");
  if (new Set(value.records.map((x) => x.id)).size !== value.records.length) throw fail("OWNERSHIP_CONTRACT_INVALID");
  const roles = value.records.filter((x) => x.kind === "test_role"), users = value.records.filter((x) => x.kind === "test_user"), calendars = value.records.filter((x) => x.kind === "user_calendar"); if (roles.length !== 1 || users.length !== 3 || calendars.length !== 3 || JSON.stringify(roles[0].permissions) !== JSON.stringify(["profile:read", "messenger:read", "messenger:write"])) throw fail("IDENTITY_TOPOLOGY_INVALID");
  const purposes = new Map(users.map((x) => [x.purpose, x])); if (!["creator", "reader", "inactive-candidate"].every((purpose) => purposes.has(purpose))) throw fail("IDENTITY_TOPOLOGY_INVALID");
  for (const user of users) if (PROTECTED.has(String(user.loginId).toLowerCase()) || user.roleId !== roles[0].id || user.companyId !== value.companyId || user.active !== true || !includesRun(user.name, runId) || !includesRun(user.loginId, runId) || !includesRun(user.email?.split("@")[0], runId)) throw fail("IDENTITY_TOPOLOGY_INVALID");
  if (!calendars.every((x) => x.isAutoDefault === true && x.companyId === value.companyId && users.some((user) => user.id === x.userId)) || new Set(calendars.map((x) => x.userId)).size !== 3) throw fail("IDENTITY_TOPOLOGY_INVALID");
  return { ownership: { runId, companyId: value.companyId, records: [...value.records] }, role: roles[0], users: purposes, owned: new Map(value.records.map((x) => [x.id, x])) };
}
function addOwned(context, records, allowed) { if (!Array.isArray(records) || !records.length) throw fail("DYNAMIC_OWNERSHIP_MISSING"); for (const row of records) { if (!DYNAMIC.has(row.kind) || !allowed.includes(row.kind) || row.ownerRunId !== context.ownership.runId || context.owned.has(row.id)) throw fail("DYNAMIC_OWNERSHIP_INVALID"); context.ownership.records.push(row); context.owned.set(row.id, row); } }
function owned(context, id, kind) { const row = context.owned.get(id); if (row?.kind !== kind) throw fail("NETWORK_DYNAMIC_OWNERSHIP_MISMATCH"); return row; }
function validateMutationTarget(item, context) {
  const itemIds = item.ids ?? [item.id]; if (!itemIds.length || itemIds.some((id) => !context.owned.has(id))) throw fail("MUTATION_OWNERSHIP_MISMATCH");
  if (item.path === "/api/v1/messenger/rooms") { if (item.method !== "POST" || item.kind !== "messenger_room" || itemIds.length !== 1) throw fail("MUTATION_OWNERSHIP_MISMATCH"); return; }
  if (item.path === "/api/v1/messenger/attachments") { if (item.method !== "POST" || item.kind !== "messenger_staged_upload" || itemIds.length !== 1) throw fail("MUTATION_OWNERSHIP_MISMATCH"); return; }
  const admin = item.path.match(/^\/api\/v1\/admin\/users\/([^/]+)$/); if (admin) { if (item.method !== "PATCH" || item.kind !== "test_user" || itemIds.length !== 1 || itemIds[0] !== admin[1]) throw fail("MUTATION_OWNERSHIP_MISMATCH"); return; }
  const roomAction = item.path.match(/^\/api\/v1\/messenger\/rooms\/([^/]+)\/(favorite|participants|messages|read)$/); if (!roomAction) throw fail("MUTATION_OWNERSHIP_MISMATCH"); owned(context, roomAction[1], "messenger_room");
  if (roomAction[2] === "messages") { if (item.method !== "POST" || item.kind !== "messenger_message" || itemIds.length !== 1 || context.owned.get(itemIds[0])?.roomId !== roomAction[1]) throw fail("MUTATION_OWNERSHIP_MISMATCH"); return; }
  if (item.kind !== "messenger_room" || itemIds[0] !== roomAction[1]) throw fail("MUTATION_OWNERSHIP_MISMATCH"); if (roomAction[2] === "participants" && (item.method !== "PATCH" || itemIds.length !== 2 || context.owned.get(itemIds[1])?.kind !== "test_user")) throw fail("MUTATION_OWNERSHIP_MISMATCH"); if (roomAction[2] === "favorite" && (item.method !== "PATCH" || itemIds.length !== 1)) throw fail("MUTATION_OWNERSHIP_MISMATCH"); if (roomAction[2] === "read" && (item.method !== "POST" || itemIds.length !== 1)) throw fail("MUTATION_OWNERSHIP_MISMATCH");
}
function assertMutations(items, network, context) { if (!Array.isArray(items)) throw fail("MUTATION_EVIDENCE_INCOMPLETE"); const mutations = network.filter((x) => x.method !== "GET"); if (items.length !== mutations.length || !sameCounts(countRoutes(items), countRoutes(mutations))) throw fail("MUTATION_EVIDENCE_INCOMPLETE"); for (const item of items) validateMutationTarget(item, context); }

function validateRoom(result, context) {
  noSecrets(result); if (result?.status !== "PASS") throw fail("MESSENGER_COMPOSITE_INCOMPLETE"); const creator = context.users.get("creator"), reader = context.users.get("reader"), inactive = context.users.get("inactive-candidate"); assertSession(result.session, creator); assertActions(result.actions, ["messenger.open", "room.create", "room.list.reread", "room.search", "room.select", "room.favorite.enable", "room.favorite.reread", "room.participants.open", "room.participants.add", "room.participants.reread", "room.reader.creator-controls-hidden"]); assertNetwork(result.network); addOwned(context, result.createdRecords, ["messenger_room", "messenger_member"]);
  const rooms = result.createdRecords.filter((x) => x.kind === "messenger_room"), members = result.createdRecords.filter((x) => x.kind === "messenger_member"), room = rooms[0]; if (rooms.length !== 1 || members.length !== 3 || room.creatorId !== creator.id || room.companyId !== context.ownership.companyId || room.roomType !== "group" || !room.nameIncludesRunId || room.retentionDays !== 14 || new Set(members.map((x) => x.userId)).size !== 3 || ![creator.id, reader.id, inactive.id].every((id) => members.some((x) => x.roomId === room.id && x.userId === id)) || members.some((x) => PROTECTED.has(String(x.userId).toLowerCase()))) throw fail("DYNAMIC_RELATION_INVALID");
  const summary = result.room; if (!summary || summary.id !== room.id || summary.creatorId !== creator.id || summary.roomType !== "group" || !summary.nameIncludesRunId || summary.retentionDays !== 14 || summary.initialParticipantCount !== 2 || summary.finalParticipantCount !== 3 || !summary.favorite || !summary.favoriteReread || !summary.sortedFirst || !summary.updatedAtChanged || !summary.creatorControlsVisible || summary.readerControlsVisible !== false || members.find((x) => x.userId === creator.id)?.isFavorite !== true) throw fail("ROOM_STATE_INVALID");
  for (const row of result.network) { const ok = (row.path === "/api/v1/messenger/rooms" && ["GET", "POST"].includes(row.method)) || (row.path === `/api/v1/messenger/rooms/${room.id}` && row.method === "GET") || (row.path === `/api/v1/messenger/rooms/${room.id}/favorite` && row.method === "PATCH") || (row.path === `/api/v1/messenger/rooms/${room.id}/participants` && row.method === "PATCH"); if (!ok) throw fail(row.path.includes("/rooms/") ? "NETWORK_DYNAMIC_OWNERSHIP_MISMATCH" : "NETWORK_ROUTE_FAMILY_INCOMPLETE"); }
  assertMutations(result.mutationOwnership, result.network, context); assertShots(result.screenshots, SHOTS.slice(0, 2).concat(SHOTS[4])); return result;
}
function validateMessages(result, context) {
  noSecrets(result); if (result?.status !== "PASS") throw fail("MESSENGER_COMPOSITE_INCOMPLETE"); const creator = context.users.get("creator"), room = [...context.owned.values()].find((x) => x.kind === "messenger_room"); assertSession(result.session, creator); assertActions(result.actions, ["message.text.send", "message.text.reread", "attachment.select", "attachment.upload", "message.file.send", "message.file.reread", "shared.files.open"]); assertNetwork(result.network); addOwned(context, result.createdRecords, ["messenger_staged_upload", "messenger_storage_object", "messenger_message", "messenger_attachment", "messenger_read"]);
  const byKind = (kind) => result.createdRecords.filter((x) => x.kind === kind), uploads = byKind("messenger_staged_upload"), objects = byKind("messenger_storage_object"), messages = byKind("messenger_message"), attachments = byKind("messenger_attachment"), reads = byKind("messenger_read"), text = messages.find((x) => x.messageType === "text"), file = messages.find((x) => x.messageType === "file"), attachment = attachments[0]; if (uploads.length !== 1 || objects.length !== 1 || messages.length !== 2 || attachments.length !== 1 || reads.length !== 2 || objects[0].uploadId !== uploads[0].id || messages.some((x) => x.roomId !== room.id || x.senderId !== creator.id || x.retentionDays !== 14) || !text?.bodyIncludesRunId || attachment.messageId !== file?.id || attachment.roomId !== room.id || attachment.uploadId !== uploads[0].id || attachment.byteSize !== result.fixture?.byteSize || attachment.mimeType !== "text/plain" || !attachment.fileNameIncludesRunId || reads.some((x) => x.roomId !== room.id || x.userId !== creator.id || !messages.some((m) => m.id === x.messageId)) || new Set(reads.map((x) => x.messageId)).size !== 2) throw fail("DYNAMIC_RELATION_INVALID");
  if (!result.fixture?.fileNameIncludesRunId || result.fixture.mimeType !== "text/plain" || result.fixture.byteSize > 1024 || !result.fixture.contentIncludesRunId || result.attachment?.id !== attachment.id || result.attachment.uploadId !== uploads[0].id || result.attachment.messageId !== file.id || result.attachment.uploadReusable !== false || result.messages?.length !== 2) throw fail("MESSAGE_STATE_INVALID");
  for (const row of result.network) { const ok = (row.path === "/api/v1/messenger/attachments" && row.method === "POST") || (row.path === `/api/v1/messenger/rooms/${room.id}/messages` && ["GET", "POST"].includes(row.method)); if (!ok) throw fail("NETWORK_ROUTE_FAMILY_INCOMPLETE"); } assertMutations(result.mutationOwnership, result.network, context); assertShots(result.screenshots, SHOTS.slice(2, 4).concat(SHOTS[5])); return result;
}
function validateRead(result, context) {
  noSecrets(result); if (result?.status !== "PASS") throw fail("MESSENGER_COMPOSITE_INCOMPLETE"); const reader = context.users.get("reader"), creator = context.users.get("creator"), room = [...context.owned.values()].find((x) => x.kind === "messenger_room"), messages = [...context.owned.values()].filter((x) => x.kind === "messenger_message"), attachment = [...context.owned.values()].find((x) => x.kind === "messenger_attachment"); assertSession(result.sessions, reader); assertSession(result.sessions, creator); assertActions(result.actions, ["room.reader.open", "messages.reader.reread", "attachment.download.click", "room.read", "room.read.idempotent", "messages.creator.reread"]); assertNetwork(result.network); addOwned(context, result.createdRecords, ["messenger_read"]);
  const reads = result.createdRecords; if (reads.length !== 2 || reads.some((x) => x.roomId !== room.id || x.userId !== reader.id || !messages.some((m) => m.id === x.messageId)) || new Set(reads.map((x) => x.messageId)).size !== 2) throw fail("DYNAMIC_RELATION_INVALID"); if (result.download?.attachmentId !== attachment.id || result.download.sameOriginStatus !== 200 || result.download.originalByteSize !== attachment.byteSize || result.read?.callCount !== 2 || result.read.auditCount !== 1 || result.read.readerId !== reader.id || new Set(result.read.messageIds ?? []).size !== 2) throw fail("READ_IDEMPOTENCY_INVALID"); if (result.messages?.length !== 2 || result.messages.some((x) => x.recipientCount !== 2 || x.readCount !== 1 || x.unreadCount !== 1 || JSON.stringify(x.readerIds) !== JSON.stringify([reader.id]))) throw fail("READ_AGGREGATE_INVALID");
  const messageIds = new Set(messages.map((x) => x.id)); for (const row of result.network) { const download = row.path.match(/^\/api\/v1\/messenger\/rooms\/([^/]+)\/messages\/([^/]+)\/attachments\/([^/]+)$/); const ok = (row.path === `/api/v1/messenger/rooms/${room.id}/messages` && row.method === "GET") || (row.path === `/api/v1/messenger/rooms/${room.id}/read` && row.method === "POST") || (download && row.method === "GET"); if (!ok) throw fail("NETWORK_ROUTE_FAMILY_INCOMPLETE"); if (download && (download[1] !== room.id || !messageIds.has(download[2]) || download[3] !== attachment.id)) throw fail("NETWORK_DYNAMIC_OWNERSHIP_MISMATCH"); } assertMutations(result.mutationOwnership, result.network, context); return result;
}
function validateInactive(result, context) {
  noSecrets(result); if (result?.status !== "PASS") throw fail("MESSENGER_COMPOSITE_INCOMPLETE"); const creator = context.users.get("creator"), reader = context.users.get("reader"), inactive = context.users.get("inactive-candidate"), room = [...context.owned.values()].find((x) => x.kind === "messenger_room"), messages = [...context.owned.values()].filter((x) => x.kind === "messenger_message"); assertSession(result.creatorSession, creator); assertSession(result.adminSession); if (!result.adminSession?.isAdministrator) throw fail("ADMIN_SESSION_REQUIRED"); assertActions(result.actions, ["admin.user.deactivate", "room.active-members.reread", "messages.active-aggregate.reread"]); assertNetwork(result.network); if (result.candidate?.id !== inactive.id || result.candidate.active !== false || !result.candidate.membershipPreserved || result.room?.id !== room.id || result.room.participantCount !== 2 || JSON.stringify(result.room.activeUserIds) !== JSON.stringify([creator.id, reader.id]) || result.room.inactiveMembershipCount !== 1 || result.messages?.length !== 2 || result.messages.some((x) => !messages.some((m) => m.id === x.id) || x.recipientCount !== 1 || x.readCount !== 1 || x.unreadCount !== 0)) throw fail("INACTIVE_AGGREGATE_INVALID");
  for (const row of result.network) { const ok = (row.path === `/api/v1/admin/users/${inactive.id}` && row.method === "PATCH") || (row.path === `/api/v1/messenger/rooms/${room.id}` && row.method === "GET") || (row.path === `/api/v1/messenger/rooms/${room.id}/messages` && row.method === "GET"); if (!ok) throw fail("NETWORK_DYNAMIC_OWNERSHIP_MISMATCH"); } assertMutations(result.mutationOwnership, result.network, context); return result;
}
function expectedAudit(row, context) { const room = [...context.owned.values()].find((x) => x.kind === "messenger_room"), messages = [...context.owned.values()].filter((x) => x.kind === "messenger_message"), creator = context.users.get("creator"), reader = context.users.get("reader"); if (row.event === "messenger.message.sent") return { actorId: creator.id, targets: new Set(messages.map((x) => x.id)) }; if (row.event === "messenger.room.read") return { actorId: reader.id, targets: new Set([room.id]) }; return { actorId: creator.id, targets: new Set([room.id]) }; }
function assertDb(e, context, runId) {
  noSecrets(e); const dbOwned = [...context.owned.values()].filter((x) => !["messenger_staged_upload", "messenger_storage_object"].includes(x.kind)), rows = e?.rows, ids = Array.isArray(rows) ? new Set(rows.map((x) => x.id)) : new Set(); if (e?.existingRowChanges !== 0 || !Array.isArray(rows) || rows.length !== ids.size || ids.size !== dbOwned.length || dbOwned.some((x) => !ids.has(x.id)) || rows.some((x) => x.ownerRunId !== runId || context.owned.get(x.id)?.kind !== x.kind)) throw fail(e?.existingRowChanges ? "EXISTING_ROW_CHANGED" : "DB_EVIDENCE_NOT_RUN_OWNED");
  const room = [...context.owned.values()].find((x) => x.kind === "messenger_room"), creator = context.users.get("creator"), reader = context.users.get("reader"), inactive = context.users.get("inactive-candidate"), messages = [...context.owned.values()].filter((x) => x.kind === "messenger_message"), attachment = [...context.owned.values()].find((x) => x.kind === "messenger_attachment"); if (e.room?.id !== room.id || e.room.creatorId !== creator.id || e.room.roomType !== "group" || !e.room.nameIncludesRunId || e.room.retentionDays !== 14 || JSON.stringify(e.room.activeMemberIds) !== JSON.stringify([creator.id, reader.id]) || e.room.inactiveMembershipUserId !== inactive.id || e.members?.length !== 3 || !e.members.some((x) => x.userId === inactive.id && x.active === false && x.membershipPreserved) || e.messages?.length !== 2 || e.attachment?.id !== attachment.id || e.attachment.messageId !== attachment.messageId || e.attachment.uploadId !== attachment.uploadId || e.attachment.byteSize !== attachment.byteSize || e.attachment.uploadReusable !== false || e.reads?.length !== 4 || new Set(e.reads.map((x) => `${x.messageId}:${x.userId}`)).size !== 4 || ![creator.id, reader.id].every((userId) => messages.every((message) => e.reads.some((x) => x.messageId === message.id && x.userId === userId))) || e.inactiveCandidateActive !== false) throw fail("DB_STATE_MISMATCH");
  const audits = e.audits ?? [], counts = countRoutes(audits.map((x) => ({ method: x.event, path: "", status: 200 }))); for (const [event, count] of AUDIT_COUNTS) if (audits.filter((x) => x.event === event).length !== count) throw fail("AUDIT_EVIDENCE_INCOMPLETE"); if (audits.length !== 6 || audits.some((row) => { const expected = expectedAudit(row, context); return row.ownerRunId !== runId || row.actorId !== expected.actorId || !expected.targets.has(row.targetId); }) || new Set(audits.filter((x) => x.event === "messenger.message.sent").map((x) => x.targetId)).size !== 2) throw fail("AUDIT_EVIDENCE_INCOMPLETE"); if (audits.some((x) => x.reasonSafe !== true)) throw fail("AUDIT_REASON_SENSITIVE"); void counts;
}
function assertStorage(e, context) { noSecrets(e); const upload = [...context.owned.values()].find((x) => x.kind === "messenger_staged_upload"), object = [...context.owned.values()].find((x) => x.kind === "messenger_storage_object"); if (e?.uploadId !== upload?.id || e.objectId !== object?.id || !e.originalExists || !e.metadataExists || e.originalByteSize !== upload.byteSize || e.fileCount !== 2 || e.withinRoot !== true) throw fail("STORAGE_EVIDENCE_INCOMPLETE"); }
function sameFp(value) { return value?.before?.exists === false ? value.after?.exists === false : value?.after?.exists === true && value.before?.fingerprint && value.before.fingerprint === value.after.fingerprint; }
function assertDbCleanup(c, context, runId) { noSecrets(c); if (c?.runId !== runId || c.residualOwnedRows !== 0 || c.residualOwnedAudit !== 0 || !c.sessionsClosed || c.existingRowChanges !== 0) throw fail("CLEANUP_INCOMPLETE"); if (context) { const identities = context.ownership.records.filter((x) => ["test_role", "test_user"].includes(x.kind)); if (c.disposableIdentities?.length !== identities.length || c.disposableIdentities.some((x) => x.active !== false || x.ownerRunId !== runId || !identities.some((i) => i.id === x.id && i.kind === x.kind))) throw fail("CLEANUP_INCOMPLETE"); } if (!["admin", "cyhuh", "ysla"].every((id) => sameFp(c.protectedAccounts?.find((x) => x.loginId === id))) || c.existingMessengerFingerprint?.before !== c.existingMessengerFingerprint?.after) throw fail("PROTECTED_ACCOUNT_CHANGED"); }
function assertStorageCleanup(c, context, runId) { noSecrets(c); const upload = context ? [...context.owned.values()].find((x) => x.kind === "messenger_staged_upload") : null, expectedIds = upload ? [upload.id] : [], expectedFiles = upload ? 2 : 0; if (c?.runId !== runId || c.residualStorageObjects !== 0 || JSON.stringify(c.deletedUploadIds) !== JSON.stringify(expectedIds) || c.deletedFileCount !== expectedFiles || c.withinRoot !== true || c.unresolvedGlobUsed !== false || c.existingStorageFingerprint?.before !== c.existingStorageFingerprint?.after) throw fail("STORAGE_CLEANUP_INCOMPLETE"); }

export async function runMessenger({ manifest, runId, browserDriver, dbDriver, storageDriver, evidenceDir }) {
  assertDrivers(browserDriver, dbDriver, storageDriver); const area = manifest.areas.find((x) => x.id === "messenger"); if (area?.status !== "READY" || area.adapter !== "messenger") throw fail("AREA_NOT_READY"); let context, room, message, read, inactive, dbEvidence, storageEvidence, dbCleanup, storageCleanup, primary, closeError, dbCleanupError, storageCleanupError;
  try { context = assertBase(await dbDriver.prepareOwnedData({ runId }), runId); room = validateRoom(await browserDriver.runMessengerRoomFlow({ runId, origin: manifest.environment.userOrigin, evidenceDir, ownership: context.ownership }), context); message = validateMessages(await browserDriver.runMessengerMessageFlow({ runId, origin: manifest.environment.userOrigin, evidenceDir, ownership: context.ownership }), context); read = validateRead(await browserDriver.runMessengerReadFlow({ runId, origin: manifest.environment.userOrigin, evidenceDir, ownership: context.ownership }), context); inactive = validateInactive(await browserDriver.runInactiveParticipantFlow({ runId, userOrigin: manifest.environment.userOrigin, adminOrigin: manifest.environment.adminOrigin, evidenceDir, ownership: context.ownership }), context); dbEvidence = await dbDriver.collectMessengerEvidence({ runId, ownership: context.ownership }); assertDb(dbEvidence, context, runId); storageEvidence = await storageDriver.collectMessengerStorageEvidence({ runId, ownership: context.ownership }); assertStorage(storageEvidence, context); } catch (error) { primary = error?.code ? error : fail("LIVE_EXECUTION_FAILED"); } finally { try { await browserDriver.close(); } catch { closeError = fail("BROWSER_CLOSE_FAILED"); } try { dbCleanup = await dbDriver.cleanupOwnedData({ runId, ownership: context?.ownership }); } catch { dbCleanupError = fail("DB_CLEANUP_FAILED"); } try { storageCleanup = await storageDriver.cleanupOwnedStorage({ runId, ownership: context?.ownership }); } catch { storageCleanupError = fail("STORAGE_CLEANUP_FAILED"); } }
  if (storageCleanupError) throw storageCleanupError; if (dbCleanupError) throw dbCleanupError; if (!dbCleanup || !storageCleanup) throw primary ?? fail("CLEANUP_REQUIRED"); assertDbCleanup(dbCleanup, context, runId); assertStorageCleanup(storageCleanup, context, runId); if (closeError) throw closeError; if (primary) throw primary;
  return { status: "PASS", areaId: "messenger", actions: { room: room.actions, message: message.actions, read: read.actions, inactive: inactive.actions }, screenshots: [...room.screenshots, ...message.screenshots], network: [...room.network, ...message.network, ...read.network, ...inactive.network], mutationOwnership: { room: room.mutationOwnership, message: message.mutationOwnership, read: read.mutationOwnership, inactive: inactive.mutationOwnership }, dbAudit: { ...dbEvidence, storage: storageEvidence }, cleanup: { db: dbCleanup, storage: storageCleanup } };
}
