import React, { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { CommonPopup } from "./components/CommonPopup";
import {
  ApiRequestError, createWorkspaceFolder, deleteWorkspaceFile, deleteWorkspaceFolder, downloadWorkspaceFile,
  favoriteWorkspaceFile, fetchWorkspaceDirectory, fetchWorkspaceFileDetail, fetchWorkspaceFiles, fetchWorkspaceFolders,
  moveWorkspaceFile, renameWorkspaceFile, renameWorkspaceFolder, restoreWorkspaceFile, saveWorkspaceFileShares,
  uploadWorkspaceFile, uploadWorkspaceFileVersion, type WorkspaceDirectory, type WorkspaceFile,
  type WorkspaceFileDetail, type WorkspaceFileScope, type WorkspaceFolder,
} from "./api";

type PopupMode = "none"|"upload"|"folder"|"folder-rename"|"folder-delete"|"version"|"rename"|"move"|"share"|"trash";
type ShareDraft = WorkspaceFileDetail["shares"];
const SCOPES:Array<[WorkspaceFileScope,string]>=[["mine","내 파일"],["shared","공유받은 파일"],["department","부서 파일"],["recent","최근"],["favorites","즐겨찾기"],["trash","휴지통"]];
const message=(error:unknown)=>error instanceof ApiRequestError||error instanceof Error?error.message:"요청을 처리하지 못했습니다.";

export function FilePanel({token,currentUserId,initialSelectionId}:{token:string;currentUserId:string;initialSelectionId?:string}){
  const [scope,setScope]=useState<WorkspaceFileScope>("mine"),[folderId,setFolderId]=useState<string|null>(null),[query,setQuery]=useState(""),[debouncedQuery,setDebouncedQuery]=useState(""),[sort,setSort]=useState("updated_desc");
  const [files,setFiles]=useState<WorkspaceFile[]>([]),[folders,setFolders]=useState<WorkspaceFolder[]>([]),[directory,setDirectory]=useState<WorkspaceDirectory>({departments:[],users:[]});
  const [selectedId,setSelectedId]=useState(initialSelectionId??""),[selectedFolderId,setSelectedFolderId]=useState<string|null>(null),[detail,setDetail]=useState<WorkspaceFileDetail|null>(null),[popupMode,setPopupMode]=useState<PopupMode>("none");
  const [listLoading,setListLoading]=useState(false),[detailLoading,setDetailLoading]=useState(false),[saving,setSaving]=useState(false),[listError,setListError]=useState(""),[detailError,setDetailError]=useState(""),[popupError,setPopupError]=useState("");
  const [name,setName]=useState(""),[initialName,setInitialName]=useState(""),[targetFolder,setTargetFolder]=useState(""),[shareDraft,setShareDraft]=useState<ShareDraft>([]),[shareTarget,setShareTarget]=useState(""),[sharePermission,setSharePermission]=useState<"viewer"|"editor">("viewer"),[uploadName,setUploadName]=useState("");
  const uploadRef=useRef<HTMLInputElement>(null),requestSequence=useRef(0);
  const selectedFolder=folders.find(folder=>folder.id===selectedFolderId)??null;
  const popupDirty=Boolean(uploadName)||name!==initialName||targetFolder!==(detail?.folderId??"")||JSON.stringify(shareDraft)!==JSON.stringify(detail?.shares??[]);
  const folderChildren=(parentId:string|null)=>folders.filter(folder=>(folder.parent_id??folder.parentId??null)===parentId);
  const shareOptions=useMemo(()=>[
    ...directory.users.filter(user=>user.id!==currentUserId).map(user=>({value:`user:${user.id}`,label:`${user.name} · ${user.department_name||"부서 없음"}`,targetType:"user" as const,targetId:user.id})),
    ...directory.departments.map(dept=>({value:`department:${dept.id}`,label:`${dept.name} 부서`,targetType:"department" as const,targetId:dept.id})),
  ],[directory,currentUserId]);

  useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedQuery(query.trim()),300);return()=>window.clearTimeout(timer);},[query]);
  async function loadList(){const sequence=++requestSequence.current;setListLoading(true);setListError("");try{const [fileResponse,folderResponse,directoryResponse]=await Promise.all([fetchWorkspaceFiles(token,{scope,folderId,query:debouncedQuery,sort}),fetchWorkspaceFolders(token),fetchWorkspaceDirectory(token)]);if(sequence!==requestSequence.current)return;setFiles(fileResponse.items);setFolders(folderResponse.items);setDirectory(directoryResponse);setSelectedId(current=>fileResponse.items.some(item=>item.id===current)?current:"");}catch(error){if(sequence===requestSequence.current)setListError(message(error));}finally{if(sequence===requestSequence.current)setListLoading(false);}}
  useEffect(()=>{void loadList();},[token,scope,folderId,debouncedQuery,sort]);
  async function loadDetail(){if(!selectedId){setDetail(null);return;}setDetailLoading(true);setDetailError("");try{setDetail(await fetchWorkspaceFileDetail(token,selectedId));}catch(error){setDetailError(message(error));setDetail(null);}finally{setDetailLoading(false);}}
  useEffect(()=>{void loadDetail();},[token,selectedId]);
  function open(mode:PopupMode,folder?:WorkspaceFolder){setPopupError("");setUploadName("");const nextName=folder?.name??detail?.file_name??"";setName(nextName);setInitialName(nextName);setSelectedFolderId(folder?.id??null);setTargetFolder(detail?.folderId??"");setShareDraft(detail?.shares.map(item=>({...item}))??[]);setShareTarget("");setPopupMode(mode);}
  function addShare(){const option=shareOptions.find(item=>item.value===shareTarget);if(!option)return;setShareDraft(current=>current.some(item=>item.target_type===option.targetType&&item.target_id===option.targetId)?current:[...current,{target_type:option.targetType,target_id:option.targetId,target_name:option.label,permission:sharePermission}]);setShareTarget("");}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setPopupError("");try{const file=uploadRef.current?.files?.[0];if(popupMode==="upload"&&file)await uploadWorkspaceFile(token,file,folderId);else if(popupMode==="version"&&file&&detail)await uploadWorkspaceFileVersion(token,detail.id,file,detail.version??0);else if(popupMode==="folder")await createWorkspaceFolder(token,name,folderId);else if(popupMode==="folder-rename"&&selectedFolder)await renameWorkspaceFolder(token,selectedFolder.id,name,selectedFolder.version);else if(popupMode==="folder-delete"&&selectedFolder)await deleteWorkspaceFolder(token,selectedFolder.id,selectedFolder.version);else if(popupMode==="rename"&&detail)await renameWorkspaceFile(token,detail.id,name,detail.version);else if(popupMode==="move"&&detail)await moveWorkspaceFile(token,detail.id,targetFolder||null,detail.version??0);else if(popupMode==="share"&&detail)await saveWorkspaceFileShares(token,detail.id,detail.version??0,shareDraft);else if(popupMode==="trash"&&detail)await deleteWorkspaceFile(token,detail.id,detail.version);else throw new Error("입력 내용을 확인하세요.");setPopupMode("none");setSelectedFolderId(null);await loadList();await loadDetail();}catch(error){setPopupError(message(error));}finally{setSaving(false);}}
  async function safeDownload(file:WorkspaceFile,version?:number){try{setDetailError("");await downloadWorkspaceFile(token,file,version);}catch(error){setDetailError(message(error));}}
  const downloadVersion=(version:number)=>detail?safeDownload(detail,version):Promise.resolve();
  async function toggleFavorite(){if(!detail)return;try{await favoriteWorkspaceFile(token,detail.id,!detail.isFavorite);await loadList();await loadDetail();}catch(error){setDetailError(message(error));}}
  async function restore(){if(!detail)return;try{await restoreWorkspaceFile(token,detail.id,detail.version??0);setSelectedId("");await loadList();}catch(error){setDetailError(message(error));}}
  function renderFolderTree(parentId:string|null,depth=0):React.ReactNode{return folderChildren(parentId).map(folder=><div className="ui043-files__folder-row" style={{paddingLeft:depth*10}} key={folder.id}><button type="button" onClick={()=>setFolderId(folder.id)} onDoubleClick={()=>setFolderId(folder.id)}>{folder.name}</button><button type="button" aria-label={`${folder.name} 이름 변경`} onClick={()=>open("folder-rename",folder)}>✎</button><button type="button" aria-label={`${folder.name} 삭제`} onClick={()=>open("folder-delete",folder)}>×</button>{renderFolderTree(folder.id,depth+1)}</div>);}

  return <section className="ui043-files" aria-label="파일 관리">
    <nav className="ui043-files__navigation"><header><h1 className="ui043-files__screen-title">파일</h1><button type="button" className="ui043-files__info" aria-label="파일 화면 설명" title="폴더와 파일을 관리하고 같은 회사의 사용자 또는 부서와 공유합니다.">i</button></header><p className="ui043-files__helper">서버 원본 파일과 공유 상태를 관리합니다.</p>{SCOPES.map(([id,label])=><button className={scope===id?"is-active":""} type="button" key={id} onClick={()=>{setScope(id);setFolderId(null);}}>{label}</button>)}{scope==="mine"?<><h2 className="ui043-files__section-title">내 폴더</h2><button type="button" onDoubleClick={()=>setFolderId(null)} onClick={()=>setFolderId(null)}>최상위</button>{renderFolderTree(null)}<button className="is-primary" type="button" onClick={()=>open("folder")}>새 폴더</button></>:null}</nav>
    <main className="ui043-files__list"><header><h2 className="ui043-files__section-title">파일 목록</h2><button className="is-primary" type="button" onClick={()=>open("upload")}>업로드</button></header><div className="ui043-files__filters"><input aria-label="파일 검색" placeholder="파일 이름 검색" value={query} onChange={event=>setQuery(event.target.value)}/><select aria-label="정렬" value={sort} onChange={event=>setSort(event.target.value)}><option value="updated_desc">최근 수정순</option><option value="name_asc">이름순</option><option value="size_desc">큰 파일순</option></select></div>{listLoading?<p>목록을 불러오는 중입니다.</p>:listError?<div role="alert">{listError}<button type="button" onClick={()=>void loadList()}>다시 시도</button></div>:files.length===0?<p>이 위치에 파일이 없습니다.</p>:<div className="ui043-files__table" role="list">{files.map(file=><button type="button" role="listitem" className={selectedId===file.id?"is-selected":""} key={file.id} onClick={()=>setSelectedId(file.id)} onDoubleClick={()=>void safeDownload(file)}><strong>{file.file_name}</strong><span>{file.content_type}</span><span>{file.size_bytes.toLocaleString()} B</span><span>{new Date(file.updated_at).toLocaleString("ko-KR")}</span></button>)}</div>}</main>
    <aside className="ui043-files__detail"><h2 className="ui043-files__section-title">파일 상세</h2>{detailLoading?<p>상세를 불러오는 중입니다.</p>:detailError?<div role="alert">{detailError}<button type="button" onClick={()=>void loadDetail()}>다시 시도</button></div>:!detail?<p>파일을 선택하세요.</p>:<><h3>{detail.file_name}</h3><dl><dt>형식</dt><dd>{detail.content_type}</dd><dt>크기</dt><dd>{detail.size_bytes.toLocaleString()} B</dd><dt>버전</dt><dd>{detail.currentVersion??1}</dd></dl><div className="ui043-files__actions"><button type="button" onClick={()=>void safeDownload(detail)}>다운로드</button><button type="button" onClick={()=>void toggleFavorite()}>{detail.isFavorite?"즐겨찾기 해제":"즐겨찾기"}</button>{detail.permissions?.newVersion?<button type="button" onClick={()=>open("version")}>새 버전</button>:null}{detail.permissions?.rename?<button type="button" onClick={()=>open("rename")}>이름 변경</button>:null}{detail.permissions?.move?<button type="button" onClick={()=>open("move")}>이동</button>:null}{detail.permissions?.share?<button type="button" onClick={()=>open("share")}>공유</button>:null}{detail.permissions?.trash&&scope!=="trash"?<button className="is-danger" type="button" onClick={()=>open("trash")}>휴지통으로 이동</button>:null}{detail.permissions?.restore&&scope==="trash"?<button type="button" onClick={()=>void restore()}>복원</button>:null}</div><h3>버전 이력</h3>{detail.versions.map(version=><p key={version.version_no}>v{version.version_no} · {new Date(version.created_at).toLocaleString("ko-KR")} <button type="button" onClick={()=>void downloadVersion(version.version_no)}>버전 다운로드</button></p>)}<h3>공유 현황</h3>{detail.shares.map(share=><p key={`${share.target_type}-${share.target_id}`}>{share.target_name||share.target_type} · {share.permission}</p>)}<h3>활동 이력</h3>{detail.activity.map((activity,index)=><p key={`${activity.created_at}-${index}`}>{activity.actor_user_name} · {activity.event}</p>)}</>}</aside>
    <CommonPopup title={{upload:"파일 업로드",folder:"새 폴더","folder-rename":"폴더 이름 변경","folder-delete":"폴더 삭제",version:"새 버전",rename:"이름 변경",move:"파일 이동",share:"공유",trash:"휴지통으로 이동",none:"파일"}[popupMode]} open={popupMode!=="none"} onClose={()=>setPopupMode("none")} saving={saving} error={popupError} dirty={popupDirty}><form onSubmit={submit}>{popupMode==="upload"||popupMode==="version"?<label>파일<input ref={uploadRef} type="file" required onChange={event=>setUploadName(event.target.files?.[0]?.name??"")}/></label>:null}{["folder","folder-rename","rename"].includes(popupMode)?<label>이름<input value={name} maxLength={255} onChange={event=>setName(event.target.value)} required/></label>:null}{popupMode==="move"?<label>대상 폴더<select value={targetFolder} onChange={event=>setTargetFolder(event.target.value)}><option value="">최상위</option>{folders.map(folder=><option value={folder.id} key={folder.id}>{folder.name}</option>)}</select></label>:null}{popupMode==="share"?<div className="ui043-files__share-editor"><label>공유 대상<select value={shareTarget} onChange={event=>setShareTarget(event.target.value)}><option value="">사용자 또는 부서 선택</option>{shareOptions.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label><label>권한 변경<select value={sharePermission} onChange={event=>setSharePermission(event.target.value as "viewer"|"editor")}><option value="viewer">viewer</option><option value="editor">editor</option></select></label><button type="button" onClick={addShare}>대상 추가</button>{shareDraft.map((share,index)=><div key={`${share.target_type}-${share.target_id}`}><span>{share.target_name} · {share.permission}</span><select aria-label={`${share.target_name} 권한 변경`} value={share.permission} onChange={event=>setShareDraft(current=>current.map((item,itemIndex)=>itemIndex===index?{...item,permission:event.target.value as "viewer"|"editor"}:item))}><option value="viewer">viewer</option><option value="editor">editor</option></select><button type="button" onClick={()=>setShareDraft(current=>current.filter((_,itemIndex)=>itemIndex!==index))}>공유 해제</button></div>)}</div>:null}{popupMode==="trash"?<p>파일은 휴지통에서 복원할 수 있습니다.</p>:null}{popupMode==="folder-delete"?<p>빈 폴더만 삭제할 수 있습니다.</p>:null}<footer><button type="button" onClick={()=>setPopupMode("none")}>취소</button><button className="is-primary" type="submit" disabled={saving}>확인</button></footer></form></CommonPopup>
  </section>;
}
