import React, { FormEvent, useEffect, useRef, useState } from "react";
import { CommonPopup } from "./components/CommonPopup";
import {
  ApiRequestError, createWorkspaceFolder, deleteWorkspaceFile, downloadWorkspaceFile, favoriteWorkspaceFile,
  fetchWorkspaceFileDetail, fetchWorkspaceFiles, fetchWorkspaceFolders, moveWorkspaceFile, renameWorkspaceFile,
  restoreWorkspaceFile, saveWorkspaceFileShares, uploadWorkspaceFile, uploadWorkspaceFileVersion,
  type WorkspaceFile, type WorkspaceFileDetail, type WorkspaceFileScope, type WorkspaceFolder,
} from "./api";

type PopupMode = "none" | "upload" | "folder" | "version" | "rename" | "move" | "share" | "trash";
const SCOPES: Array<[WorkspaceFileScope, string]> = [["mine","내 파일"],["shared","공유받은 파일"],["department","부서 파일"],["recent","최근"],["favorites","즐겨찾기"],["trash","휴지통"]];
const message = (error: unknown) => error instanceof ApiRequestError || error instanceof Error ? error.message : "요청을 처리하지 못했습니다.";

export function FilePanel({ token, initialSelectionId }: { token: string; initialSelectionId?: string }) {
  const [scope,setScope]=useState<WorkspaceFileScope>("mine"), [folderId,setFolderId]=useState<string|null>(null), [query,setQuery]=useState(""), [debouncedQuery,setDebouncedQuery]=useState("");
  const [sort,setSort]=useState("updated_desc"), [files,setFiles]=useState<WorkspaceFile[]>([]), [folders,setFolders]=useState<WorkspaceFolder[]>([]);
  const [selectedId,setSelectedId]=useState(initialSelectionId ?? ""), [detail,setDetail]=useState<WorkspaceFileDetail|null>(null), [popupMode,setPopupMode]=useState<PopupMode>("none");
  const [listLoading,setListLoading]=useState(false), [detailLoading,setDetailLoading]=useState(false), [saving,setSaving]=useState(false), [listError,setListError]=useState(""), [detailError,setDetailError]=useState(""), [popupError,setPopupError]=useState("");
  const [name,setName]=useState(""), [targetFolder,setTargetFolder]=useState(""), [shareTarget,setShareTarget]=useState(""), [sharePermission,setSharePermission]=useState<"viewer"|"editor">("viewer");
  const uploadRef=useRef<HTMLInputElement>(null), requestSequence=useRef(0);

  useEffect(()=>{ const timer=window.setTimeout(()=>setDebouncedQuery(query.trim()),300); return()=>window.clearTimeout(timer); },[query]);
  async function loadList(){ const sequence=++requestSequence.current; setListLoading(true); setListError(""); try { const [fileResponse,folderResponse]=await Promise.all([fetchWorkspaceFiles(token,{scope,folderId,query:debouncedQuery,sort}),fetchWorkspaceFolders(token)]); if(sequence!==requestSequence.current)return; setFiles(fileResponse.items); setFolders(folderResponse.items); setSelectedId(current=>fileResponse.items.some(item=>item.id===current)?current:""); } catch(error){ if(sequence===requestSequence.current)setListError(message(error)); } finally { if(sequence===requestSequence.current)setListLoading(false); } }
  useEffect(()=>{ void loadList(); },[token,scope,folderId,debouncedQuery,sort]);
  async function loadDetail(){ if(!selectedId){setDetail(null);return;} setDetailLoading(true);setDetailError("");try{setDetail(await fetchWorkspaceFileDetail(token,selectedId));}catch(error){setDetailError(message(error));setDetail(null);}finally{setDetailLoading(false);}}
  useEffect(()=>{void loadDetail();},[token,selectedId]);
  function open(mode:PopupMode){setPopupError("");setName(detail?.file_name??"");setTargetFolder(detail?.folderId??"");setShareTarget("");setPopupMode(mode);}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setPopupError("");try{const file=uploadRef.current?.files?.[0];if(popupMode==="upload"&&file)await uploadWorkspaceFile(token,file,folderId);else if(popupMode==="version"&&file&&detail)await uploadWorkspaceFileVersion(token,detail.id,file,detail.version??0);else if(popupMode==="folder")await createWorkspaceFolder(token,name,folderId);else if(popupMode==="rename"&&detail)await renameWorkspaceFile(token,detail.id,name,detail.version);else if(popupMode==="move"&&detail)await moveWorkspaceFile(token,detail.id,targetFolder||null,detail.version??0);else if(popupMode==="share"&&detail&&shareTarget)await saveWorkspaceFileShares(token,detail.id,detail.version??0,[...detail.shares,{target_type:"user",target_id:shareTarget,permission:sharePermission}]);else if(popupMode==="trash"&&detail)await deleteWorkspaceFile(token,detail.id,detail.version);else throw new Error("입력 내용을 확인하세요.");setPopupMode("none");await loadList();await loadDetail();}catch(error){setPopupError(message(error));}finally{setSaving(false);}}
  async function toggleFavorite(){if(!detail)return;try{await favoriteWorkspaceFile(token,detail.id,!detail.isFavorite);await loadList();await loadDetail();}catch(error){setDetailError(message(error));}}
  async function restore(){if(!detail)return;try{await restoreWorkspaceFile(token,detail.id,detail.version??0);setSelectedId("");await loadList();}catch(error){setDetailError(message(error));}}

  return <section className="ui043-files" aria-label="파일 관리">
    <nav className="ui043-files__navigation"><h2>파일</h2>{SCOPES.map(([id,label])=><button className={scope===id?"is-active":""} type="button" key={id} onClick={()=>{setScope(id);setFolderId(null);}}>{label}</button>)}<h3>폴더</h3><button type="button" onClick={()=>setFolderId(null)}>최상위</button>{folders.map(folder=><button type="button" key={folder.id} onClick={()=>setFolderId(folder.id)}>{folder.name}</button>)}<button className="is-primary" type="button" onClick={()=>open("folder")}>새 폴더</button></nav>
    <main className="ui043-files__list"><header><h1>파일 목록</h1><button className="is-primary" type="button" onClick={()=>open("upload")}>업로드</button></header><div className="ui043-files__filters"><input aria-label="파일 검색" placeholder="파일 이름 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated_desc">최근 수정순</option><option value="name_asc">이름순</option><option value="size_desc">큰 파일순</option></select></div>{listLoading?<p>목록을 불러오는 중입니다.</p>:listError?<div role="alert">{listError}<button type="button" onClick={()=>void loadList()}>다시 시도</button></div>:files.length===0?<p>이 위치에 파일이 없습니다.</p>:<div className="ui043-files__table" role="list">{files.map(file=><button type="button" role="listitem" className={selectedId===file.id?"is-selected":""} key={file.id} onClick={()=>setSelectedId(file.id)}><strong>{file.file_name}</strong><span>{file.content_type}</span><span>{file.size_bytes.toLocaleString()} B</span><span>{new Date(file.updated_at).toLocaleString("ko-KR")}</span></button>)}</div>}</main>
    <aside className="ui043-files__detail"><h2>파일 상세</h2>{detailLoading?<p>상세를 불러오는 중입니다.</p>:detailError?<div role="alert">{detailError}<button type="button" onClick={()=>void loadDetail()}>다시 시도</button></div>:!detail?<p>파일을 선택하세요.</p>:<><h3>{detail.file_name}</h3><dl><dt>형식</dt><dd>{detail.content_type}</dd><dt>크기</dt><dd>{detail.size_bytes.toLocaleString()} B</dd><dt>버전</dt><dd>{detail.currentVersion??1}</dd></dl><div className="ui043-files__actions"><button type="button" onClick={()=>void downloadWorkspaceFile(token,detail)}>다운로드</button><button type="button" onClick={()=>void toggleFavorite()}>{detail.isFavorite?"즐겨찾기 해제":"즐겨찾기"}</button>{detail.permissions?.newVersion?<button type="button" onClick={()=>open("version")}>새 버전</button>:null}{detail.permissions?.rename?<button type="button" onClick={()=>open("rename")}>이름 변경</button>:null}{detail.permissions?.move?<button type="button" onClick={()=>open("move")}>이동</button>:null}{detail.permissions?.share?<button type="button" onClick={()=>open("share")}>공유</button>:null}{detail.permissions?.trash&&scope!=="trash"?<button className="is-danger" type="button" onClick={()=>open("trash")}>휴지통으로 이동</button>:null}{detail.permissions?.restore&&scope==="trash"?<button type="button" onClick={()=>void restore()}>복원</button>:null}</div><h3>버전 이력</h3>{detail.versions.map(version=><p key={version.version_no}>v{version.version_no} · {new Date(version.created_at).toLocaleString("ko-KR")}</p>)}<h3>공유 현황</h3>{detail.shares.map(share=><p key={`${share.target_type}-${share.target_id}`}>{share.target_type} · {share.permission}</p>)}<h3>활동 이력</h3>{detail.activity.map((activity,index)=><p key={`${activity.created_at}-${index}`}>{activity.actor_user_name} · {activity.event}</p>)}</>}</aside>
    <CommonPopup title={{upload:"파일 업로드",folder:"새 폴더",version:"새 버전",rename:"이름 변경",move:"파일 이동",share:"공유",trash:"휴지통으로 이동",none:"파일"}[popupMode]} open={popupMode!=="none"} onClose={()=>setPopupMode("none")} saving={saving} error={popupError} dirty><form onSubmit={submit}>{popupMode==="upload"||popupMode==="version"?<label>파일<input ref={uploadRef} type="file" required/></label>:null}{popupMode==="folder"||popupMode==="rename"?<label>이름<input value={name} maxLength={255} onChange={e=>setName(e.target.value)} required/></label>:null}{popupMode==="move"?<label>대상 폴더<select value={targetFolder} onChange={e=>setTargetFolder(e.target.value)}><option value="">최상위</option>{folders.map(folder=><option value={folder.id} key={folder.id}>{folder.name}</option>)}</select></label>:null}{popupMode==="share"?<><label>사용자 ID<input value={shareTarget} onChange={e=>setShareTarget(e.target.value)} required/></label><label>권한<select value={sharePermission} onChange={e=>setSharePermission(e.target.value as "viewer"|"editor")}><option value="viewer">viewer</option><option value="editor">editor</option></select></label></>:null}{popupMode==="trash"?<p>파일은 휴지통에서 복원할 수 있습니다.</p>:null}<footer><button type="button" onClick={()=>setPopupMode("none")}>취소</button><button className="is-primary" type="submit" disabled={saving}>확인</button></footer></form></CommonPopup>
  </section>;
}
